attach(mtcars)
opar<-par(no.readnonly=TRUE)
par(mfrow=c(2,2))
plot(wt,mpg,main="wt-mpg plot")
hist(wt,main="wt hist");
boxplot(wt,main="wt boxplot")
a<-head(wt)
b<-head(mpg)
plot(a,b,type="b")
detach(mtcars)